-- =========================================================
-- jour j — Supabase Database Schema & RLS Security Policies
-- Slogan: "Le moment qu'on attend"
-- Target: Algerian Wedding & Event Venues / Traiteurs (Oran, Algeria)
-- =========================================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES TABLE (Admins & Business Owners)
create table if not exists public.profiles (
  id uuid primary key default uuid_generate_v4(),
  full_name text not null,
  phone text,
  email text unique not null,
  role text not null check (role in ('admin', 'owner')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. CATEGORIES TABLE (e.g., قاعة الأعراس, Traiteur, ...)
create table if not exists public.categories (
  id text primary key,
  name text not null,
  description text,
  image_url text,
  active boolean default true not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. BUSINESSES TABLE (Venues, Caterers, Service Providers)
create table if not exists public.businesses (
  id text primary key,
  category_id text references public.categories(id) on delete cascade not null,
  owner_id uuid references public.profiles(id) on delete set null,
  name text not null,
  title text not null,
  description text,
  phone text not null,
  email text,
  address text not null,
  location text default 'وهران، الجزائر',
  price numeric not null,
  price_unit text default 'دج',
  rating numeric default 5.0 check (rating >= 1.0 and rating <= 5.0),
  main_image text not null,
  active boolean default true not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. PORTFOLIO TABLE (Gallery Photos)
create table if not exists public.portfolio (
  id uuid primary key default uuid_generate_v4(),
  business_id text references public.businesses(id) on delete cascade not null,
  image_url text not null,
  title text,
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. AVAILABILITY TABLE (Working Days: السبت - الجمعة)
create table if not exists public.availability (
  id uuid primary key default uuid_generate_v4(),
  business_id text references public.businesses(id) on delete cascade not null,
  day text not null check (day in ('السبت', 'الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة')),
  available boolean default true not null,
  unique(business_id, day)
);

-- 6. REGISTRATION_LINKS TABLE (Secret Invitation Tokens generated by Admin)
create table if not exists public.registration_links (
  id uuid primary key default uuid_generate_v4(),
  business_id text references public.businesses(id) on delete cascade not null,
  token text unique not null,
  used boolean default false not null,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- =========================================================
-- STORAGE BUCKETS CONFIGURATION (Supabase Storage)
-- =========================================================
insert into storage.buckets (id, name, public) 
values ('business-images', 'business-images', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public) 
values ('portfolio', 'portfolio', true)
on conflict (id) do nothing;

-- =========================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =========================================================

-- Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.businesses enable row level security;
alter table public.portfolio enable row level security;
alter table public.availability enable row level security;
alter table public.registration_links enable row level security;

-- Public Visitors (Unauthenticated): READ ONLY on active public data
create policy "Public can view active categories" 
  on public.categories for select 
  using (active = true);

create policy "Public can view active businesses" 
  on public.businesses for select 
  using (active = true);

create policy "Public can view portfolio for active businesses" 
  on public.portfolio for select 
  using (exists (select 1 from public.businesses where id = portfolio.business_id and active = true));

create policy "Public can view availability for active businesses" 
  on public.availability for select 
  using (exists (select 1 from public.businesses where id = availability.business_id and active = true));

-- Admins: FULL ACCESS across all tables
create policy "Admin full access profiles" 
  on public.profiles for all 
  using (auth.uid() in (select id from public.profiles where role = 'admin'));

create policy "Admin full access categories" 
  on public.categories for all 
  using (auth.uid() in (select id from public.profiles where role = 'admin'));

create policy "Admin full access businesses" 
  on public.businesses for all 
  using (auth.uid() in (select id from public.profiles where role = 'admin'));

create policy "Admin full access portfolio" 
  on public.portfolio for all 
  using (auth.uid() in (select id from public.profiles where role = 'admin'));

create policy "Admin full access availability" 
  on public.availability for all 
  using (auth.uid() in (select id from public.profiles where role = 'admin'));

create policy "Admin full access registration_links" 
  on public.registration_links for all 
  using (auth.uid() in (select id from public.profiles where role = 'admin'));

-- Business Owners: Can ONLY view & edit their assigned business
create policy "Owner can view own business" 
  on public.businesses for select 
  using (owner_id = auth.uid());

create policy "Owner can update own business" 
  on public.businesses for update 
  using (owner_id = auth.uid());

create policy "Owner can manage own portfolio" 
  on public.portfolio for all 
  using (exists (select 1 from public.businesses where id = portfolio.business_id and owner_id = auth.uid()));

create policy "Owner can manage own availability" 
  on public.availability for all 
  using (exists (select 1 from public.businesses where id = availability.business_id and owner_id = auth.uid()));

-- =========================================================
-- INITIAL SEED DATA
-- =========================================================

-- 1. Seed Categories
insert into public.categories (id, name, description, image_url, active) values
  ('wedding-halls', 'قاعة الأعراس', 'أفخم وأرقى قاعات الحفلات والأعراس المصممة لأجمل الليالي', 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=80', true),
  ('traiteur', 'Traiteur', 'أشهى المأكولات الجزائرية والعالمية وبوفيهات الحلويات الراقية للمناسبات', 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=1200&q=80', true)
on conflict (id) do nothing;

-- 2. Seed Businesses
insert into public.businesses (id, category_id, name, title, description, phone, email, address, location, price, price_unit, rating, main_image, active) values
  (
    'salle-el-louloua', 
    'wedding-halls', 
    'قاعة اللؤلؤة', 
    'قاعة اللؤلؤة للأعراس والاحتفالات الفاخرة',
    'قاعة راقية متكاملة تتسع لأكثر من 500 ضيف، مزودة بأحدث أنظمة الإضاءة الليزرية، ديكورات ملكية ذهبية، جناح خاص للعروسين، ومواقف سيارات واسعة ومحروسة.',
    '+213 555 12 34 56',
    'contact@el-louloua-oran.dz',
    'حي العقيد لطفي، بالقرب من الواجهة البحرية',
    'وهران، الجزائر',
    120000,
    'دج',
    4.9,
    'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=80',
    true
  ),
  (
    'saveurs-doran', 
    'traiteur', 
    'Saveurs d''Oran Traiteur', 
    'خدمات الإطعام الفاخر والبوفيهات الملكية للأعراس والمؤتمرات',
    'نقدم أرقى تشكيلات الأطباق التقليدية الجزائرية (طاجين الزيتون، الشواء، الحريرة الوهرانية) بالإضافة إلى بوفيهات مقبلات عالمية، حلويات شرقية وغربية، وتنسيق طاولات فاخر.',
    '+213 661 98 76 54',
    'traiteur@saveurs-oran.dz',
    'شارع العربي بن مهيدي، وسط المدينة',
    'وهران، الجزائر',
    3500,
    'دج / شخص',
    4.8,
    'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=1200&q=80',
    true
  )
on conflict (id) do nothing;

-- 3. Seed Portfolio for قاعة اللؤلؤة
insert into public.portfolio (business_id, image_url, title, sort_order) values
  ('salle-el-louloua', 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=800&q=80', 'ديكور القاعة الملكي', 1),
  ('salle-el-louloua', 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=800&q=80', 'تنسيق الطاولات والورود', 2),
  ('salle-el-louloua', 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=800&q=80', 'كوشة العروسين والإضاءة', 3),
  ('salle-el-louloua', 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=800&q=80', 'إضاءة المسرح والأعراس', 4),
  ('salle-el-louloua', 'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?auto=format&fit=crop&w=800&q=80', 'بوفيه الضيافة والاستقبال', 5);

-- 4. Seed Portfolio for Saveurs d'Oran Traiteur
insert into public.portfolio (business_id, image_url, title, sort_order) values
  ('saveurs-doran', 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=800&q=80', 'أطباق رئيسية فاخرة', 1),
  ('saveurs-doran', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80', 'مقبلات وسلطات برستيج', 2),
  ('saveurs-doran', 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80', 'حلويات جزائرية وشرقية', 3),
  ('saveurs-doran', 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80', 'أطباق فاخرة ولحوم مشوية', 4),
  ('saveurs-doran', 'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?auto=format&fit=crop&w=800&q=80', 'بوفيه فواكه وعصائر طازجة', 5);

-- 5. Seed Availability Days (Saturday to Friday)
insert into public.availability (business_id, day, available) values
  ('salle-el-louloua', 'السبت', true),
  ('salle-el-louloua', 'الأحد', true),
  ('salle-el-louloua', 'الإثنين', false),
  ('salle-el-louloua', 'الثلاثاء', true),
  ('salle-el-louloua', 'الأربعاء', true),
  ('salle-el-louloua', 'الخميس', true),
  ('salle-el-louloua', 'الجمعة', true),

  ('saveurs-doran', 'السبت', true),
  ('saveurs-doran', 'الأحد', true),
  ('saveurs-doran', 'الإثنين', true),
  ('saveurs-doran', 'الثلاثاء', true),
  ('saveurs-doran', 'الأربعاء', true),
  ('saveurs-doran', 'الخميس', true),
  ('saveurs-doran', 'الجمعة', true)
on conflict (business_id, day) do update set available = excluded.available;

-- 6. Seed Sample Registration Link (Token: ABC123XYZ and 7Fh82Ks91Lm)
insert into public.registration_links (business_id, token, used, expires_at) values
  ('salle-el-louloua', 'ABC123XYZ', false, timezone('utc'::text, now() + interval '30 days')),
  ('saveurs-doran', '7Fh82Ks91Lm', false, timezone('utc'::text, now() + interval '30 days'))
on conflict (token) do nothing;
